service: green-car-wash

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    memorySize: 128
    region: us-east-2
    timeout: 15

functions:
    lambda:
        handler: lambda.handler
        events: 
            - http: ANY {proxy+}
            - http: ANY /